# Project: 项目3
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o test_Discrete.o Uniform_random.o Normal_random.o test_Uniform.o test_Normal.o
LINKOBJ  = main.o test_Discrete.o Uniform_random.o Normal_random.o test_Uniform.o test_Normal.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = 随机数的统计分布测试.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

test_Discrete.o: test_Discrete.c
	$(CC) -c test_Discrete.c -o test_Discrete.o $(CFLAGS)

Uniform_random.o: Uniform_random.c
	$(CC) -c Uniform_random.c -o Uniform_random.o $(CFLAGS)

Normal_random.o: Normal_random.c
	$(CC) -c Normal_random.c -o Normal_random.o $(CFLAGS)

test_Uniform.o: test_Uniform.c
	$(CC) -c test_Uniform.c -o test_Uniform.o $(CFLAGS)

test_Normal.o: test_Normal.c
	$(CC) -c test_Normal.c -o test_Normal.o $(CFLAGS)
